### PR TITLE
Revert "Remote command fix: left trim the "Reflector" argument."

### PR DESCRIPTION
**Pull request by g4klx**
Reverts g4klx/M17Gateway#10

### CODE REVIEW

**Comment by f1rmb** [comment]
Hi,

   is there any problem to revert to #10 and #11 ?

Cheers.
...
Daniel

**Comment by g4klx** [comment]
Yes. It was causing big problems with many users connecting to M17-M17. I thought it was safer to revert them all.
I will start re-adding parts of those patches over time. 
Jonathan G4KLX 


Sent from Yahoo Mail for iPhone


On Thursday, January 20, 2022, 07:27, Daniel Caujolle-Bert ***@***.***> wrote:




Hi,

is there any problem to revert to #10 and #11 ?

Cheers.
...
Daniel

**Comment by f1rmb** [comment]
Oh, okay.
Well, I will check this now too.

**Comment by f1rmb** [comment]
Maybe the reconnection is the culprit, as I don't see any problems with the other parts (trim and signal handling).

**Comment by f1rmb** [comment]
I just raised 2 PR, one for the trim, one for the signals handling. The reconnection part, which looks problematic, has been left out.

**Pull request merged**
